#if !canImport(ObjectiveC)
   import XCTest

   extension BLECentralManagerTests {
      // DO NOT MODIFY: This is autogenerated, use:
      //   `swift test --generate-linuxmain`
      // to regenerate.
      static let __allTests__BLECentralManagerTests = [
         ("testConnectToBirdbrainBLEUARTPeripheralSuccess", testConnectToBirdbrainBLEUARTPeripheralSuccess),
         ("testConnectToNonExistentPeripheral", testConnectToNonExistentPeripheral),
         ("testCubeTowerRxNotify", testCubeTowerRxNotify),
         ("testDisonnectFromNonExistentPeripheral", testDisonnectFromNonExistentPeripheral),
         ("testInit", testInit),
         ("testIsPropertySupported", testIsPropertySupported),
         ("testLinuxTestSuiteIncludesAllTests", testLinuxTestSuiteIncludesAllTests),
         ("testScanDiscoverSuccessForBirdbrainBLEUARTPeripheral", testScanDiscoverSuccessForBirdbrainBLEUARTPeripheral),
         ("testScanRediscoverSuccessForBirdbrainBLEUARTPeripheral", testScanRediscoverSuccessForBirdbrainBLEUARTPeripheral),
         ("testScanTimeout", testScanTimeout),
         ("testScanWhenAlreadyScanning", testScanWhenAlreadyScanning),
         ("testWriteBySettingCubeTowerLEDs", testWriteBySettingCubeTowerLEDs),
      ]
   }

   public func __allTests() -> [XCTestCaseEntry] {
      return [
         testCase(BLECentralManagerTests.__allTests__BLECentralManagerTests),
      ]
   }
#endif
